# 파일 입출력 

## 파일처리

ndarrary의 정보를 파일로 저장할 수 있다

일반적인 파일 확장자는 npy를 사용한다

> 파일저장(tofile)

In [5]:
import numpy as np
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.45021034  0.01404065 -0.92600124 -0.35074008  1.04900629]
 [-0.68134128 -0.53993554  0.20884546 -0.1023329   2.48757503]
 [-1.63058113 -0.20804777  0.72446725  0.16439305  0.03936667]]


> 파일 불러오기(fromfile)

In [8]:
m = np.fromfile('C:/STUDY/StudyPython22/jupyter/Numpy/n.npy')
print(m)

[-0.45021034  0.01404065 -0.92600124 -0.35074008  1.04900629 -0.68134128
 -0.53993554  0.20884546 -0.1023329   2.48757503 -1.63058113 -0.20804777
  0.72446725  0.16439305  0.03936667]


> 파일저장, 불러오기 (np.save, np.load)

In [9]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.45021034  0.01404065 -0.92600124 -0.35074008  1.04900629]
 [-0.68134128 -0.53993554  0.20884546 -0.1023329   2.48757503]
 [-1.63058113 -0.20804777  0.72446725  0.16439305  0.03936667]]


In [10]:
# n.tofile 저장한 n.npy 
# np.load('n.npy') 오류 
np.load('n.npy') 

ValueError: Cannot load file containing pickled data when allow_pickle=False